2018-01-31 14:31:46.5441|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.Exception: The authorization header is either empty or isn't Basic.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 56
   at Vsb.UrgentApp.API.Controllers.PatientController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-01-31 15:37:31.8002|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 15:39:30.6194|DEBUG|Vsb.UrgentApp.API.WebApiApplication|NHibernate.Cfg.HibernateConfigException: An exception occurred parsing configuration :The 'name' attribute is invalid - The value 'use_outer_join' is invalid according to its datatype 'String' - The Enumeration constraint failed. ---> System.Xml.Schema.XmlSchemaValidationException: The 'name' attribute is invalid - The value 'use_outer_join' is invalid according to its datatype 'String' - The Enumeration constraint failed. ---> System.Xml.Schema.XmlSchemaException: The Enumeration constraint failed.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at NHibernate.Cfg.XmlSchemas.ConfigSettingsValidationEventHandler(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String[] args, Exception innerException)
   at System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(Object value, SchemaAttDef attdef)
   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
   at System.Xml.XsdValidatingReader.ValidateAttributes()
   at System.Xml.XsdValidatingReader.ProcessElementEvent()
   at System.Xml.XsdValidatingReader.ProcessReaderEvent()
   at System.Xml.XsdValidatingReader.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(XmlReader reader, XmlSpace space)
   at NHibernate.Cfg.ConfigurationSchema.HibernateConfiguration..ctor(XmlReader hbConfigurationReader, Boolean fromAppSetting)
   at NHibernate.Cfg.Configuration.Configure(XmlReader textReader)
   at NHibernate.Cfg.Configuration.Configure(String fileName, Boolean ignoreSessionFactoryConfig)
   at SharpArch.NHibernate.NHibernateSession.ConfigureNHibernate(String cfgFile, IDictionary`2 cfgProperties) in z:\Builds\work\4c910366963b38a7\Solutions\SharpArch.NHibernate\NHibernateSession.cs:line 374
   at SharpArch.NHibernate.NHibernateSession.AddConfiguration(String factoryKey, String[] mappingAssemblies, AutoPersistenceModel autoPersistenceModel, String cfgFile, IDictionary`2 cfgProperties, String validatorCfgFile, IPersistenceConfigurer persistenceConfigurer) in z:\Builds\work\4c910366963b38a7\Solutions\SharpArch.NHibernate\NHibernateSession.cs:line 124
   at SharpArch.NHibernate.NHibernateSession.Init(ISessionStorage storage, String[] mappingAssemblies, AutoPersistenceModel autoPersistenceModel, String cfgFile, IDictionary`2 cfgProperties, String validatorCfgFile, IPersistenceConfigurer persistenceConfigurer) in z:\Builds\work\4c910366963b38a7\Solutions\SharpArch.NHibernate\NHibernateSession.cs:line 320
   at SharpArch.NHibernate.NHibernateSession.Init(ISessionStorage storage, String[] mappingAssemblies, AutoPersistenceModel autoPersistenceModel, String cfgFile) in z:\Builds\work\4c910366963b38a7\Solutions\SharpArch.NHibernate\NHibernateSession.cs:line 260
   at Vsb.UrgentApp.API.WebApiConfig.InitNHibernate(WebSessionStorage session, String[] mappingAssemblies) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\App_Start\WebApiConfig.cs:line 48
   at Vsb.UrgentApp.API.WebApiConfig.<>c__DisplayClass0_1.<InitializeNHibernate>b__0() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\App_Start\WebApiConfig.cs:line 38
   at SharpArch.NHibernate.NHibernateInitializer.InitializeNHibernateOnce(Action initMethod) in z:\Builds\work\4c910366963b38a7\Solutions\SharpArch.NHibernate\NHibernateInitializer.cs:line 53
   at Vsb.UrgentApp.API.WebApiConfig.InitializeNHibernate(WebSessionStorage session) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\App_Start\WebApiConfig.cs:line 38
   at Vsb.UrgentApp.API.WebApiApplication.Application_BeginRequest(Object sender, EventArgs e) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Global.asax.cs:line 37
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
2018-01-31 15:39:42.7292|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 15:40:27.5056|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 15:40:50.5454|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientGET exception message: The authorization header is either empty or isn't Basic.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-01-31 15:40:50.5454|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: The authorization header is either empty or isn't Basic.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 55
   at Vsb.UrgentApp.API.Controllers.PatientController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-01-31 16:02:30.9843|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 16:09:20.3487|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 16:14:11.3893|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 18:57:17.5827|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 19:07:44.9161|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 19:10:00.8740|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 19:14:17.2522|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 20:50:29.2995|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 20:53:15.7984|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 20:55:15.0940|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 21:01:10.2977|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 21:09:47.7408|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 21:09:55.1635|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientGET exception message: A task was canceled.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-01-31 21:09:55.1650|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientGET exception message: The authorization header is either empty or isn't Basic.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-01-31 21:09:55.1650|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-01-31 21:09:55.1650|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: The authorization header is either empty or isn't Basic.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 55
   at Vsb.UrgentApp.API.Controllers.PatientController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-01-31 21:11:42.8256|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 22:55:24.2543|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 22:55:29.2123|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientGET exception message: The authorization header is either empty or isn't Basic.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-01-31 22:55:29.2123|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: The authorization header is either empty or isn't Basic.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 55
   at Vsb.UrgentApp.API.Controllers.PatientController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-01-31 23:02:22.7994|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 23:04:44.4981|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-01-31 23:08:35.8199|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 09:38:17.0165|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 09:39:16.3440|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 09:42:16.5727|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 09:57:05.0965|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 10:06:10.8289|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 10:14:05.6432|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 10:20:46.4489|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 10:24:51.3955|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 10:27:02.0042|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-01 22:32:10.3290|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:07:52.3058|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:09:12.3161|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:22:18.8679|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:23:50.7640|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:28:04.1304|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:34:32.8972|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:35:23.7355|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientPOST exception message: could not insert: [Vsb.UrgentApp.Domain.DomainObjects.Entities.TagRegistration#9][SQL: INSERT INTO TagRegistration (Tag_Id, Patient_Id, Created, Id) VALUES (?, ?, ?, ?)] - violation of PRIMARY or UNIQUE KEY constraint "UNQ1_TAGREGISTRATION" on table "TAGREGISTRATION"
Problematic key value is ("TAG_ID" = 1). Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-02-02 01:35:23.7355|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|NHibernate.Exceptions.GenericADOException: could not insert: [Vsb.UrgentApp.Domain.DomainObjects.Entities.TagRegistration#9][SQL: INSERT INTO TagRegistration (Tag_Id, Patient_Id, Created, Id) VALUES (?, ?, ?, ?)] ---> FirebirdSql.Data.FirebirdClient.FbException: violation of PRIMARY or UNIQUE KEY constraint "UNQ1_TAGREGISTRATION" on table "TAGREGISTRATION"
Problematic key value is ("TAG_ID" = 1) ---> FirebirdSql.Data.Common.IscException: violation of PRIMARY or UNIQUE KEY constraint "UNQ1_TAGREGISTRATION" on table "TAGREGISTRATION"
Problematic key value is ("TAG_ID" = 1)
   at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ProcessResponse(IResponse response) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\Client\Managed\Version10\GdsDatabase.cs:line 639
   at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponse() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\Client\Managed\Version10\GdsDatabase.cs:line 671
   at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadGenericResponse() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\Client\Managed\Version10\GdsDatabase.cs:line 679
   at FirebirdSql.Data.Client.Managed.Version12.GdsStatement.Execute() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\Client\Managed\Version12\GdsStatement.cs:line 79
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommand(CommandBehavior behavior, Boolean returnsSet) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 1221
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 480
   --- End of inner exception stack trace ---
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 493
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.AdoNet.NonBatchingBatcher.AddToBatch(IExpectation expectation)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Boolean[] notNull, Int32 j, SqlCommandInfo sql, Object obj, ISessionImplementor session)
   --- End of inner exception stack trace ---
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Boolean[] notNull, Int32 j, SqlCommandInfo sql, Object obj, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at SharpArch.NHibernate.LinqRepositoryWithTypedId`2.Save(T entity) in z:\Builds\work\4c910366963b38a7\Solutions\SharpArch.NHibernate\LinqRepositoryWithTypedId.cs:line 53
   at Vsb.UrgentApp.Tasks.Patient.PatientTasks.Create(PatientDto patientDto, Boolean createTagRegistration) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\Patient\PatientTasks.cs:line 153
   at Vsb.UrgentApp.API.Controllers.PatientController.Post(String action, PatientDto patient) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 100
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-02-02 01:39:27.6553|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:42:42.6600|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:49:05.4464|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:53:46.9110|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 01:56:05.6032|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-02 02:00:25.0817|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-02-27 10:51:06.6463|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-28 19:16:20.8270|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-28 19:16:33.8048|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagEventGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:16:33.8048|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagEventController.Get(Int32 tagId) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagEventController.cs:line 65
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:16:46.0452|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagEventGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:16:46.0452|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagEventController.Get(Int32 tagId) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagEventController.cs:line 65
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:31:48.1732|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-28 19:31:54.7829|ERROR|Vsb.UrgentApp.Common.Mappers.BaseMapper|Trying to map this date: 28.03.2018 13:10:20
2018-03-28 19:34:07.3516|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-28 19:34:12.6243|ERROR|Vsb.UrgentApp.Common.Mappers.BaseMapper|Trying to map this date: 28.03.2018 13:10:20
2018-03-28 19:56:12.5325|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-28 19:58:10.1059|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagRegistrationGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:10.1059|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagEventTypeGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:10.1339|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagEventTypeController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagEventTypeController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:10.1339|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagRegistrationController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagRegistrationController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:10.4645|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:10.4645|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagController.cs:line 39
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:10.8219|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:10.8454|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.PatientController.Get(Nullable`1 showDeleted, Nullable`1 maxPatients) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 55
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:10.9300|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: PatientGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:10.9300|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.PatientController.Get(Nullable`1 showDeleted, Nullable`1 maxPatients) in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\PatientController.cs:line 55
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:11.0180|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagEventTypeGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:11.0180|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagEventTypeController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagEventTypeController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:11.0636|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagRegistrationGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:11.0636|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagRegistrationController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagRegistrationController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 19:58:11.3479|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagGET exception message: Name or password is incorrect.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-28 19:58:11.3479|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.UnauthorizedAccessException: Name or password is incorrect.
   at Vsb.UrgentApp.Tasks.User.UserTasks.GetAuthenticatedUser() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.Tasks\User\UserTasks.cs:line 52
   at Vsb.UrgentApp.API.Controllers.TagController.Get() in C:\Users\trannann\Desktop\work\cak3\rtls\sw\src\SesterskaAplikace\backend\Vsb.UrgentApp.UI\Vsb.UrgentApp.API\Controllers\TagController.cs:line 39
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-28 21:41:30.6990|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-29 19:19:01.3724|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-03-30 10:08:19.3933|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagEventTypeGET exception message: A task was canceled.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-30 10:08:19.3923|DEBUG|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|Rest v1: TagGET exception message: A task was canceled.. Arguments: System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-03-30 10:08:19.4113|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-03-30 10:08:19.4123|ERROR|Vsb.UrgentApp.API.Filters.HttpExceptionFilter|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-06-07 20:38:02.5349|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 21:07:26.7024|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 21:23:05.4045|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 21:32:09.9405|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 21:45:08.6544|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 21:53:00.2936|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 21:56:38.2789|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 22:05:54.9782|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-07 23:11:52.9816|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-08 09:27:42.9035|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-06-08 10:40:40.8218|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-09-11 19:05:22.9685|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
2018-09-11 19:08:08.1478|INFO|Vsb.UrgentApp.Infrastructure.Db.FireBirdConnection|Database connection established.
